#!/usr/bin/env python3
"""Build the Intuit API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Custom Fields': 'Custom Fields',
    'Payroll Time': 'Payroll Time',
}

LINES = [
    {
        "name": 'Intuit Platform',
        "color": '#0077C5',
        "stations": [
        ('Platform', (260, 200)),
        ('Accounting', (420, 175)),
        ('Payments', (580, 165)),
        ('Payroll Time', (740, 175)),
        ('Desktop', (900, 200)),
        ],
    },
    {
        "name": 'QuickBooks Modules',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Projects', (820, 530)),
        ('Custom Fields', (910, 600)),
        ('Sales Tax', (730, 600)),
        ],
    },
]

URL_OVERRIDES = {
    'Platform': 'https://apis.apis.io/apis/intuit/intuit/',
    'Accounting': 'https://apis.apis.io/apis/intuit/quickbooks-accounting/',
    'Payments': 'https://apis.apis.io/apis/intuit/quickbooks-payments/',
    'Payroll Time': 'https://apis.apis.io/apis/intuit/quickbooks-payroll-time/',
    'Desktop': 'https://apis.apis.io/apis/intuit/quickbooks-desktop/',
    'Projects': 'https://apis.apis.io/apis/intuit/quickbooks-projects/',
    'Custom Fields': 'https://apis.apis.io/apis/intuit/quickbooks-custom-fields/',
    'Sales Tax': 'https://apis.apis.io/apis/intuit/quickbooks-sales-tax/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Intuit API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: intuit/openapi · github.com/api-evangelist/intuit',
        out_dir=Path(__file__).resolve().parent,
        out_basename='intuit-subway-map',
        provider_id='intuit',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
